version: '3'
services:
  nginx:
    image: cust-nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/sites-enabled:/etc/nginx/conf.d
      - phpsocket:/var/run

  php:
    build:
      context: ./docker/php
      args:
        fpm_listen: /var/run/php-fpm.sock
#        fpm_listen: 127.0.0.1:9000
    volumes:
      - ./www:/var/www
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./conf/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - phpsocket:/var/run
volumes:
  phpsocket: