version: '3'
services:
  nginx:
    image: maximus905/nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/sites-enabled:/etc/nginx/conf.d
      - phpsocket:/var/run

  php:
    image: maximus905/php-fpm-socket:7.2.10-socket

    volumes:
      - ./www:/var/www
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - phpsocket:/var/run
volumes:
  phpsocket: