version: '3'
services:
  nginx:
    image: maximus905/nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/sites-enabled:/etc/nginx/conf.d
      - phpsocket:/var/run

  php:
    image: test
#    image: maximus905/php-fpm-socket:7.2.10-socket
#    build:
#      context: https://github.com/Maximus905/docker-php-fpm.git#7.2.10
#      args:
#        fpm_listen: /var/run/php-fpm.sock
#        fpm_listen: 127.0.0.1:9000
    volumes:
      - ./www:/var/www
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
      - ./conf/php/custom.d:/usr/local/etc/php/custom.d
      - phpsocket:/var/run
volumes:
  phpsocket: